-- ====================================================
-- VERIFICAR ESTRUCTURA EXACTA DE LA TABLA CLIENTES
-- ====================================================

SELECT 'ESTRUCTURA COMPLETA DE LA TABLA CLIENTES:' as info;
DESCRIBE clientes;

SELECT 'CAMPOS DISPONIBLES EN LA TABLA CLIENTES:' as info;
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_COMMENT
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'clientes' 
AND TABLE_SCHEMA = DATABASE()
ORDER BY ORDINAL_POSITION;

SELECT 'ALGUNOS DATOS EXISTENTES EN CLIENTES:' as info;
SELECT * FROM clientes LIMIT 3;

SELECT 'TOTAL DE REGISTROS EN CLIENTES:' as info;
SELECT COUNT(*) as total_clientes FROM clientes; 